name = "hsr-optimizer"
main = "src/worker.js"
compatibility_date = "2026-07-16"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hsr-optimizer"
database_id = "bbbdaf21-ffd8-43ca-b898-830e3cd347ea"
migrations_dir = "migrations"

[observability]
enabled = true
